environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    CHANNEL: nightly
  - TARGET: x86_64-pc-windows-msvc
    CHANNEL: beta
  - TARGET: x86_64-pc-windows-msvc
    CHANNEL: stable
  - TARGET: x86_64-pc-windows-msvc
    CHANNEL: 1.26.2
  - TARGET: x86_64-pc-windows-gnu
    CHANNEL: stable
  - TARGET: x86_64-pc-windows-gnu
    CHANNEL: beta
  - TARGET: i686-pc-windows-msvc
    CHANNEL: stable
  - TARGET: i686-pc-windows-msvc
    CHANNEL: beta
  - TARGET: i686-pc-windows-gnu
    CHANNEL: stable
  - TARGET: i686-pc-windows-gnu
    CHANNEL: beta

install:
  - ps: >-
        If ($Env:TARGET -eq 'x86_64-pc-windows-gnu') {
          $Env:PATH += ';C:\msys64\mingw64\bin'
        } ElseIf ($Env:TARGET -eq 'i686-pc-windows-gnu') {
          $Env:PATH += ';C:\MinGW\bin'
        }
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %CHANNEL% --default-host %TARGET%
  - SET PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo build --verbose
  - cargo test --verbose
