language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.25.0
cache: cargo
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - libxxf86vm-dev
    - libosmesa6-dev
script:
  - cargo build
  - cargo test --verbose
